# Generated by Django 3.2.19 on 2023-05-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='excerpt',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='method',
        ),
    ]
