# Generated by Django 3.2.19 on 2023-05-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230520_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(choices=[(0, 'Starter'), (1, 'Main Course'), (2, 'Dessert'), (3, 'Other')], default=1),
        ),
    ]
