# Generated by Django 3.2.19 on 2023-05-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230520_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ManyToManyField(related_name='recipe_of_day', to='blog.Recipe')),
            ],
        ),
    ]
