# Generated by Django 3.2.19 on 2023-05-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_recipeofday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeOfDay',
        ),
    ]
