# Generated by Django 3.2.19 on 2023-05-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_recipeofday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_of_day',
            new_name='recipe_of_day',
        ),
        migrations.CreateModel(
            name='RecipeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_day', to='blog.recipe')),
            ],
        ),
    ]
