# Generated by Django 3.2.19 on 2023-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230521_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeofday',
            name='test',
            field=models.CharField(default='10 mins', max_length=200),
        ),
    ]
