# Generated by Django 3.2.19 on 2023-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_recipeofday_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeofday',
            name='test',
        ),
        migrations.AddField(
            model_name='recipeofday',
            name='category',
            field=models.ManyToManyField(to='blog.Recipe'),
        ),
    ]
