# Generated by Django 3.2.19 on 2023-05-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230521_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeOfDay',
        ),
    ]
