# Generated by Django 3.2.19 on 2023-05-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_recipeofday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_of_day',
        ),
        migrations.DeleteModel(
            name='RecipeOfDay',
        ),
    ]
