# Generated by Django 3.2.19 on 2023-05-25 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_auto_20230521_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='blogrecipe_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
