# Generated by Django 3.2.19 on 2023-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
