# Generated by Django 3.2.19 on 2023-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_recipe_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
