# Generated by Django 3.2.19 on 2023-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='website',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='website_url',
            field=models.URLField(blank=True, default='-'),
        ),
    ]
