# Generated by Django 3.2.19 on 2023-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20230618_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
